Move secure array in example team configs
gejohnston/imperative-wiki-next pull request #2
Opened 2021-05-25 19:45 UTC by t1m0thyj

Update the wiki docs to reflect changes in https://github.com/zowe/imperative/pull/611

2021-05-25 20:36 UTC, awharn approved these changes

2021-05-26 13:45 UTC, zFernand0 approved these changes
LGTM 😋

2021-06-01 13:13 UTC, gejohnston requested changes
I suggest one change of wording. Otherwise it looks good to me.

In the "Example configurations" section, the following statement is between the first and second example.

      This example is identical to first example except for the secure array at the end.

I suggest that we change it to:

      This example is identical to the first example except that LPAR1 and LPAR2 each contain a secure array, instead of just one secure array in the my_base profile .

2021-06-01 13:44 UTC, gejohnston approved these changes
Thanks for cleaning up the old wording.

2021-06-02 17:07 UTC, merged